before_script:
  - "mysql -e 'create database if not exists session_test; create user \'session_test\'@\'localhost\' identified by \'password\'; grant all on session_test.* to \'session_test\'@\'localhost\' identified by \'password\';'"

language: node_js
node_js:
  - "0.10"
  - "0.8"
  - "0.6"